version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radio4000-player-vue
    hostname: radio4000-player-vue
    ports:
      - "4000:4002"
    volumes:
      - ./src:/app/src
